### PR TITLE
docs: fix syntax for dirs with slashes

### PR DESCRIPTION
**Pull request by jmreicha**
Docs for the fix discovered in https://github.com/infracost/infracost-atlantis/issues/43.

### CODE REVIEW

**Comment by jmreicha** [comment]
Feel free to take this one over if needed, I wasn't sure if all references need updated.

**Comment by aliscott** [comment]
Thanks @jmreicha yeah this looks great! You're right that all references need updated - just giving it a quick test on my dev Atlantis and then will merge.

**Review by aliscott — APPROVED** [review]
Works great, thanks.

**Comment by zohairraza** [comment]
Hello Guys

I have a atlantis and infracost running on a VM instead of Docker and I am getting this error:

exit status 2: running "echo /tmp/${BASE_REPO_OWNER}-${BASE_REPO_NAME}-${PULL_NUM}-${WORKSPACE}-${REPO_REL_DIR//\\//-}-infracost.json" in "/var/spool/atlantis/repos/a-b-c/base/1152/acc": 
sh: 1: Bad substitution

**Comment by vdmgolub** [comment]
@zohairraza Hello! Thanks for reporting! It seems like the syntax we're using is valid for `/bin/bash`, however your error message suggests that you run it in `/bin/sh` which doesn't support some bash functionality. Can you share more where you use these commands? If it's a shell script, for example, you can replace the first line with `#!/bin/bash` to make it work.

**Comment by zohairraza** [comment]
Thanks for responding, yes we figured that out 
We have multiple workspaces and somehow atlantis was using /bin/sh 

We used this approach to fix it :

* also noticed later that show command was necessary in plan

      - show
      - env:
          name: INFRACOST_OUTPUT
          command: echo /tmp/${BASE_REPO_OWNER}-${BASE_REPO_NAME}-${PULL_NUM}-${WORKSPACE}-$(echo $REPO_REL_DIR | sed "s/\\//-/g")-infracost.json

**Comment by vdmgolub** [comment]
@zohairraza Awesome! Nice solution! We may need to add a Troubleshooting section to Atlantis docs to make it more visible. Thanks for posting it! 👍 

If I may ask about your impressions, did it work as you expected? And were there any other issues with our example to get it working?

**Comment by zohairraza** [comment]
Hey sorry for delayed response 

Yes it works as expected and it's awesome, just found one issue that I thought could be important to look into.

In GKE, when you add a load balancer via ingress, infracost doesn't recognise the change

**Comment by vdmgolub** [comment]
@zohairraza No worries! Thank you for letting us know! :) Is it possible to share an example with Terraform resources so we could reproduce the issue and then fix it?

**Comment by zohairraza** [comment]
Here is the resource, the ingress is configured via istio 

resource "kubernetes_manifest" "ingress" {
  manifest = {
    "apiVersion" : "networking.k8s.io/v1",
    "kind" : "Ingress",
    "metadata" : {
      "name" : "instrument-gke-ingress-${var.suffix}",
      "namespace" : kubernetes_namespace.monitoring.metadata[0].name,
      "annotations" : {
        "kubernetes.io/ingress.allow-http" : "false",
        "kubernetes.io/ingress.class" : "gce",
        "kubernetes.io/ingress.global-static-ip-name" : "instrument-ingress-ip-${var.suffix}",
        "networking.gke.io/managed-certificates" : "instrument-cert",
        "networking.gke.io/v1beta1.FrontendConfig" : "instrument-ingress-frontendconfig-${var.suffix}"
      },
    },
    "spec" : {
      "rules" : [
        {
          "http" : {
            "paths" : [
              {
                "backend" : {
                  "service" : {
                    "name" : "grafana",
                    "port" : {
                      "number" : 3000
                    }
                  }
                },
                "path" : "/grafana",
                "pathType" : "Prefix"
              }
              
            ]
          },
        },
      ]
    },
  }

**Comment by vdmgolub** [comment]
@zohairraza Thank you! I'm afraid Infracost doesn't support this resource yet thus it can't show the costs for it. We list currently supported resources here: https://www.infracost.io/docs/supported_resources/google/. Feel free to create a new GH issue requesting this resource support. This way we can get community's attention to get upvotes. We prioritize adding the new resources based on that.

**Pull request merged**
